name: hikari_novel_flutter
description: An app for reading wenku8, refactor with flutter
publish_to: none
version: 0.1.0-beta.1+1
environment:
  sdk: '>=3.9.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.3.3
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  flutter_inappwebview: ^6.1.5
  material_symbols_icons: ^4.2815.1
  amicons: ^1.0.1
  device_info_plus: ^12.3.0
  dynamic_color: ^1.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  hive_ce: ^2.11.1
  hive_ce_flutter: ^2.3.0
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  cached_network_image: ^3.4.1
  html: ^0.15.4
  catcher_2: ^2.1.2
  logger: ^2.5.0
  charset_converter: ^2.3.0
  enough_convert: ^1.6.0
  jiffy: ^6.4.3
  responsive_grid_list: ^1.4.0
  easy_refresh: ^3.4.0
  flutter_widget_from_html: ^0.17.1
  expandable_text: 2.3.0
  photo_view: ^0.15.0
  permission_handler: ^11.3.1
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.2.2
  flex_color_picker: ^3.7.1
  package_info_plus: ^9.0.0
  blur: ^4.0.0
  wakelock_plus: ^1.3.2
  battery_plus: ^7.0.0
  file_picker: ^10.2.0
  ttf_metadata: ^0.0.6
  intl: ^0.20.2
  json_annotation: ^4.9.0
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7
  pub_semver: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  hive_ce_generator: ^1.9.1
  json_serializable: ^6.10.0
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true
  assets:
  - assets/images/
flutter_native_splash:
  color: '#ffffff'
  image: assets/images/logo_transparent.png
  color_dark: '#121212'
  image_dark: assets/images/logo_transparent.png
  android_12:
    image: assets/images/logo_transparent.png
    icon_background_color: '#ffffff'
    image_dark: assets/images/logo_transparent.png
    icon_background_color_dark: '#121212'
  web: false
flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/logo.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/images/logo.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: assets/images/logo.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/images/logo.png
