name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Verify APK exists
        run: test -f build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_REGION: auto
        run: |
          aws s3 cp build/app/outputs/flutter-apk/app-release.apk \
            s3://ci-builds/app.apk \
            --endpoint-url ${{ secrets.S3_API }}

      - name: Generate Signed URL
        id: signed
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_REGION: auto
        run: |
          URL=$(aws s3 presign s3://ci-builds/app.apk \
            --expires-in 86400 \
            --endpoint-url ${{ secrets.S3_API }}
          )

          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Send Link to Telegram
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TG_CHAT }} \
            -d $'text=New build ready:\n${{ steps.signed.outputs.url }}'
